pipeline {
    agent any
    
    environment
    {
        DB_PASSWORD='myd@t@b@$3'
    }
    
    tools
    {
        maven 'M3'
    }

    stages 
    {
        stage('Build') 
        {
            steps 
            {
                git branch: 'main', url: 'https://github.com/btarceneaux/ICIN-Bank-Web-App.git'
                sh 'mvn -f com.icin/pom.xml clean compile'
            }
        }
        stage('Test')
        {
            steps
            {
                sh 'mvn -f com.icin/pom.xml test'
            }
        }
        stage('Package')
        {
            steps
            {
                sh 'mvn -f com.icin/pom.xml package'
            }
        }

    }
}
